# -*- coding: utf-8 -*-
"""
Created on Wed Apr 26 22:11:17 2017

@author: joel
"""

import tweepy, sys, time

argfile = str(sys.argv[1]) #Tak in the second argument plugged in on the command line. THis will be our input text file

CONSUMER_KEY = ''  #Note: These next 4 variable must be generated by the user's twitter account
CONSUMER_SECRET = ''
ACCESS_KEY = '' 
ACCESS_SECRET = ''


auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth.set_access_token(ACCESS_KEY, ACCESS_SECRET)
api = tweepy.API(auth)
 
filename=open(argfile,'r') #open up the argument file
f=filename.readlines() #Read in each line into a variable called f
filename.close() #close that file

for line in f:
    #Every 15 minutes, read out another one of those lines in f from the text file.
    api.update_status(line)
    time.sleep(900)#Tweet every 15 minutes